global:
 scrape_interval: 10s
 evaluation_interval: 10s

rule_files:
- "/etc/alertmanager/alert.rules"

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets:
{% for host in groups["prometheus"] %}
        - "{{host}}:{{prometheus_port}}"
{%  endfor %}

  - job_name: 'zookeeper'
    static_configs:
      - targets:
{% for host in groups["zookeepers"] %}
        - "{{host}}:8080"
{%  endfor %}

  - job_name: 'kafka-brokers'
    static_configs:
      - targets:
{% for host in groups["brokers"] %}
        - "{{host}}:8088"
{%  endfor %}

  - job_name: 'ksql'
    static_configs:
      - targets:
{% for host in groups["ksqldb"] %}
        - "{{host}}:7088"
{%  endfor %}

  - job_name: 'schema-register'
    static_configs:
      - targets:
{% for host in groups["schema"] %}
        - "{{host}}:7088"  
{%  endfor %}

  - job_name: 'node'
    static_configs:
      - targets:
{% for host in groups["all"] %}
        - "{{host}}:9100"  
{%  endfor %}

{% if "dockers" in groups %}
  - job_name: 'docker'
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
    static_configs:
      - targets: 
{% for host in groups["dockers"] %}
        - "{{host}}:9323"
{% endfor %}
{% endif %}

{% if "dockers" in groups %}
  - job_name: 'cadvisor'
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
    static_configs:
      - targets: 
{% for host in groups["dockers"] %}
        - "{{host}}:8080"
{% endfor %}
{% endif %}

  - job_name: 'pushgateway'
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
    honor_labels: true
    static_configs:
      - targets:
        - '{{groups["monitor"][0]}}:{{prometheus_push_proxy_port}}'

{% for key, value in uservice_prometheus_ports.items() %}
  - job_name: 'u_service: {{ key }}'
    static_configs:
      - targets:
        - "isusrv1:{{value}}"
{%  endfor %}
